import '../globals.css';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { setDefaultOptions } from 'date-fns';
import { enGB, zhHK } from 'date-fns/locale';
import type { Metadata, Viewport } from 'next';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { Inter as FontSans } from 'next/font/google';
import { notFound } from 'next/navigation';

import { RegisterServiceWorker } from '@/app/_components/register-service-worker';
import { ThemeProvider } from '@/app/_components/theme-provider';
import { Toaster } from '@/app/_components/ui/sonner';
import { routing } from '@/i18n/routing';
import { cn } from '@/lib/utils';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Visa Calculator',
  description: 'Generated by create next app',
  manifest: '/manifest.webmanifest',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'Visa Tracker',
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'oklch(1 0 0)' },
    { media: '(prefers-color-scheme: dark)', color: 'oklch(0.145 0 0)' },
  ],
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  setDefaultOptions({ locale: locale === 'en' ? enGB : zhHK });
  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen font-sans antialiased flex items-center justify-center',
          fontSans.variable
        )}
      >
        <NextIntlClientProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
        <Toaster position="bottom-center" />
        <SpeedInsights />
        <RegisterServiceWorker />
      </body>
    </html>
  );
}
